In [4]:
import pandas as pd
import numpy as np

In [5]:
pd.set_option('display.max_rows', None) # display all rows

In [6]:
TablaMortalidad_df = pd.read_excel("Tablas PER 2000 básicas.xls", sheet_name="PERMP", header=1)

In [7]:
TablaMortalidad_df.head()

,x+t,"qx+t, tabla base",λx+t,Unnamed: 3,Probabilidad anual de muerte,Unnamed: 5,Unnamed: 6
0,0,0.005742,0.015,NaN,Año nacim. generación,NaN,1950.000000
1,1,0.000565,0.015,NaN,Edad en 2000 (x),NaN,50.000000
2,2,0.000300,0.015,NaN,Período (t),NaN,1.000000
3,3,0.000266,0.015,NaN,"qx+t, año",NaN,0.003618
4,4,0.000225,0.015,NaN,NaN,NaN,NaN

In [8]:
TablaMortalidad_df.reindex(TablaMortalidad_df["x+t"])

,x+t,"qx+t, tabla base",λx+t,Unnamed: 3,Probabilidad anual de muerte,Unnamed: 5,Unnamed: 6
x+t,,,,,,,
0,0,0.005742,0.0150,NaN,Año nacim. generación,NaN,1950.000000
1,1,0.000565,0.0150,NaN,Edad en 2000 (x),NaN,50.000000
2,2,0.000300,0.0150,NaN,Período (t),NaN,1.000000
3,3,0.000266,0.0150,NaN,"qx+t, año",NaN,0.003618
4,4,0.000225,0.0150,NaN,NaN,NaN,NaN
5,5,0.000218,0.0150,NaN,NaN,NaN,NaN
6,6,0.000198,0.0150,NaN,NaN,NaN,NaN
7,7,0.000191,0.0150,NaN,NaN,NaN,NaN
8,8,0.000177,0.0150,NaN,NaN,NaN,NaN
9,9,0.000171,0.0150,NaN,NaN,NaN,NaN
10,10,0.000164,0.0150,NaN,NaN,NaN,NaN
11,11,0.000178,0.0150,NaN,NaN,NaN,NaN
12,12,0.000184,0.0150,NaN,NaN,NaN,NaN
13,13,0.000219,0.0150,NaN,NaN,NaN,NaN
14,14,0.000267,0.0150,NaN,NaN,NaN,NaN
15,15,0.000362,0.0150,NaN,NaN,NaN,NaN
16,16,0.000506,0.0150,NaN,NaN,NaN,NaN
17,17,0.000657,0.0150,NaN,NaN,NaN,NaN
18,18,0.000774,0.0150,NaN,NaN,NaN,NaN
19,19,0.000871,0.0150,NaN,NaN,NaN,NaN
20,20,0.000976,0.0150,NaN,NaN,NaN,NaN
21,21,0.001011,0.0150,NaN,NaN,NaN,NaN
22,22,0.001082,0.0150,NaN,NaN,NaN,NaN
23,23,0.001139,0.0150,NaN,NaN,NaN,NaN
24,24,0.001182,0.0150,NaN,NaN,NaN,NaN
25,25,0.001170,0.0150,NaN,NaN,NaN,NaN
26,26,0.001193,0.0150,NaN,NaN,NaN,NaN
27,27,0.001237,0.0150,NaN,NaN,NaN,NaN
28,28,0.001281,0.0150,NaN,NaN,NaN,NaN
29,29,0.001298,0.0150,NaN,NaN,NaN,NaN
30,30,0.001265,0.0150,NaN,NaN,NaN,NaN
31,31,0.001227,0.0150,NaN,NaN,NaN,NaN
32,32,0.001252,0.0150,NaN,NaN,NaN,NaN
33,33,0.001255,0.0150,NaN,NaN,NaN,NaN
34,34,0.001245,0.0150,NaN,NaN,NaN,NaN
35,35,0.001222,0.0150,NaN,NaN,NaN,NaN
36,36,0.001192,0.0150,NaN,NaN,NaN,NaN
37,37,0.001182,0.0150,NaN,NaN,NaN,NaN
38,38,0.001271,0.0150,NaN,NaN,NaN,NaN
39,39,0.001391,0.0150,NaN,NaN,NaN,NaN
40,40,0.001476,0.0150,NaN,NaN,NaN,NaN
41,41,0.001587,0.0150,NaN,NaN,NaN,NaN
42,42,0.001698,0.0150,NaN,NaN,NaN,NaN
43,43,0.001784,0.0150,NaN,NaN,NaN,NaN
44,44,0.001910,0.0150,NaN,NaN,NaN,NaN
45,45,0.002066,0.0150,NaN,NaN,NaN,NaN
46,46,0.002270,0.0150,NaN,NaN,NaN,NaN
47,47,0.002384,0.0150,NaN,NaN,NaN,NaN
48,48,0.002499,0.0150,NaN,NaN,NaN,NaN
49,49,0.002914,0.0150,NaN,NaN,NaN,NaN
50,50,0.003281,0.0150,NaN,NaN,NaN,NaN
51,51,0.003673,0.0150,NaN,NaN,NaN,NaN
52,52,0.004001,0.0150,NaN,NaN,NaN,NaN
53,53,0.004773,0.0150,NaN,NaN,NaN,NaN
54,54,0.005061,0.0150,NaN,NaN,NaN,NaN
55,55,0.005445,0.0150,NaN,NaN,NaN,NaN
56,56,0.005812,0.0150,NaN,NaN,NaN,NaN
57,57,0.006313,0.0150,NaN,NaN,NaN,NaN
58,58,0.006869,0.0150,NaN,NaN,NaN,NaN
59,59,0.007298,0.0150,NaN,NaN,NaN,NaN
60,60,0.008220,0.0150,NaN,NaN,NaN,NaN
61,61,0.009014,0.0150,NaN,NaN,NaN,NaN
62,62,0.009735,0.0150,NaN,NaN,NaN,NaN
63,63,0.010516,0.0150,NaN,NaN,NaN,NaN
64,64,0.011676,0.0150,NaN,NaN,NaN,NaN
65,65,0.013030,0.0150,NaN,NaN,NaN,NaN
66,66,0.014067,0.0150,NaN,NaN,NaN,NaN
67,67,0.015440,0.0150,NaN,NaN,NaN,NaN
68,68,0.017005,0.0150,NaN,NaN,NaN,NaN
69,69,0.018509,0.0150,NaN,NaN,NaN,NaN
70,70,0.019978,0.0150,NaN,NaN,NaN,NaN
71,71,0.021915,0.0150,NaN,NaN,NaN,NaN
72,72,0.024454,0.0150,NaN,NaN,NaN,NaN
73,73,0.027179,0.0150,NaN,NaN,NaN,NaN
74,74,0.030224,0.0150,NaN,NaN,NaN,NaN
75,75,0.033450,0.0150,NaN,NaN,NaN,NaN
76,76,0.036722,0.0150,NaN,NaN,NaN,NaN
77,77,0.040242,0.0150,NaN,NaN,NaN,NaN
78,78,0.044188,0.0150,NaN,NaN,NaN,NaN
79,79,0.048813,0.0150,NaN,NaN,NaN,NaN
80,80,0.053538,0.0150,NaN,NaN,NaN,NaN
81,81,0.059260,0.0150,NaN,NaN,NaN,NaN
82,82,0.065282,0.0150,NaN,NaN,NaN,NaN
83,83,0.070833,0.0150,NaN,NaN,NaN,NaN
84,84,0.075905,0.0150,NaN,NaN,NaN,NaN
85,85,0.083305,0.0150,NaN,NaN,NaN,NaN
86,86,0.091956,0.0150,NaN,NaN,NaN,NaN
87,87,0.099296,0.0150,NaN,NaN,NaN,NaN
88,88,0.108338,0.0150,NaN,NaN,NaN,NaN
89,89,0.119043,0.0150,NaN,NaN,NaN,NaN
90,90,0.130597,0.0150,NaN,NaN,NaN,NaN
91,91,0.142610,0.0150,NaN,NaN,NaN,NaN
92,92,0.156378,0.0135,NaN,NaN,NaN,NaN
93,93,0.170348,0.0120,NaN,NaN,NaN,NaN
94,94,0.185547,0.0105,NaN,NaN,NaN,NaN
95,95,0.200079,0.0090,NaN,NaN,NaN,NaN
96,96,0.215749,0.0075,NaN,NaN,NaN,NaN
97,97,0.232644,0.0060,NaN,NaN,NaN,NaN
98,98,0.250862,0.0045,NaN,NaN,NaN,NaN
99,99,0.271072,0.0030,NaN,NaN,NaN,NaN
100,100,0.292911,0.0015,NaN,NaN,NaN,NaN
101,101,0.324890,0.0000,NaN,NaN,NaN,NaN
102,102,0.347570,0.0000,NaN,NaN,NaN,NaN
103,103,0.371835,0.0000,NaN,NaN,NaN,NaN
104,104,0.397793,0.0000,NaN,NaN,NaN,NaN
105,105,0.425563,0.0000,NaN,NaN,NaN,NaN
106,106,0.455272,0.0000,NaN,NaN,NaN,NaN
107,107,0.487055,0.0000,NaN,NaN,NaN,NaN
108,108,0.510801,0.0000,NaN,NaN,NaN,NaN
109,109,0.535704,0.0000,NaN,NaN,NaN,NaN
110,110,0.561821,0.0000,NaN,NaN,NaN,NaN
111,111,0.589211,0.0000,NaN,NaN,NaN,NaN
112,112,0.617937,0.0000,NaN,NaN,NaN,NaN
113,113,0.648064,0.0000,NaN,NaN,NaN,NaN
114,114,0.679659,0.0000,NaN,NaN,NaN,NaN
115,115,1.000000,0.0000,NaN,NaN,NaN,NaN

In [9]:
TablaMortalidad_df.columns

Index(['x+t', 'qx+t, tabla base', 'λx+t', 'Unnamed: 3',
       'Probabilidad anual de muerte', 'Unnamed: 5', 'Unnamed: 6'],
      dtype='object')

In [10]:
TablaFiltrada_df = TablaMortalidad_df.drop(labels = ["x+t", "Unnamed: 3", "Probabilidad anual de muerte", 'Unnamed: 5', 'Unnamed: 6' ], axis = 1)

In [11]:
t_list = []
for i in range(0, len(TablaFiltrada_df["qx+t, tabla base"])):
    t_list.append(i)
TablaFiltrada_df.insert(loc = 0, column = "t", value = t_list)

In [12]:
import math
def q_x(qx, mejora, t):
    '''
    La función q_x(x, mejora) recibe la probabilidad de muerte qx de la tabla de mortalidad y el factor de mejora de ésta
    Devuelve la probabilidad de muerte qx ajustada por el factor de mejora.
    '''
    return qx*math.exp(-mejora*t)

In [13]:
g = int(input("Introduce el año de nacimiento x: "))

x_mas_t = 2000 - g

print("La edad que tenia esta persona en el año 2000 es: ", x_mas_t, " años")

La edad que tenia esta persona en el año 2000 es:  36  años

In [14]:
TablaResultados_df = TablaFiltrada_df.copy()

In [15]:
TablaResultados_df.head()

   t  qx+t, tabla base   λx+t
0  0          0.005742  0.015
1  1          0.000565  0.015
2  2          0.000300  0.015
3  3          0.000266  0.015
4  4          0.000225  0.015

In [16]:
x_mas_t_list = []
for i in range(0, len(TablaResultados_df["qx+t, tabla base"])):
    x_mas_t_list.append(x_mas_t + i)
TablaResultados_df.insert(loc = 1, column="x+t", value = x_mas_t_list)

In [17]:
Tabla_Mortalidad_final = TablaResultados_df.merge(TablaFiltrada_df, left_on= "x+t", right_on= "t", how = "left")

In [18]:
Tabla_Mortalidad_final = Tabla_Mortalidad_final.drop(labels = ["t_y", "qx+t, tabla base_x", "λx+t_x" ], axis = 1)
Tabla_Mortalidad_final.head()

   t_x  x+t  qx+t, tabla base_y  λx+t_y
0    0   36            0.001192   0.015
1    1   37            0.001182   0.015
2    2   38            0.001271   0.015
3    3   39            0.001391   0.015
4    4   40            0.001476   0.015

In [19]:
Calculos = []
for i in range(0, len(Tabla_Mortalidad_final["qx+t, tabla base_y"])):
    Calculos.append(q_x(Tabla_Mortalidad_final["qx+t, tabla base_y"][i],
                        Tabla_Mortalidad_final["λx+t_y"][i], 
                        Tabla_Mortalidad_final["t_x"][i] ))
    
    #Tengo que buscar en la tabla de mortalidad filtrada la qx a partir del valor x+t como primer parámetro
    #de igual manera buscar el factor de mejora como segundo parámetro
    #como tercer parámetro es suficiente con usar el valor t que siempre es el mismo independientemente de la generación (g)
    
Tabla_Mortalidad_final.insert(loc=4, column = "q_x", value = Calculos)

In [20]:
Tabla_Mortalidad_final.rename(columns={"t_x": "t", "qx+t, tabla base_y": "qx+t, tabla base", "λx+t_y": "λx+t"}, inplace=True)

In [21]:
Mortality_Table = Tabla_Mortalidad_final.drop(labels = ["qx+t, tabla base", "λx+t"], axis = 1)
Mortality_Table.head()

   t  x+t       q_x
0  0   36  0.001192
1  1   37  0.001164
2  2   38  0.001233
3  3   39  0.001330
4  4   40  0.001390

In [22]:
Mortality_Table['lx'] = 0  
Mortality_Table.loc[0, 'lx'] = 1_000_000  

# Calculamos lx y dx fila por fila
for i in range(1, len(Mortality_Table)):
    Mortality_Table.loc[i, 'lx'] = Mortality_Table.loc[i-1, 'lx'] * (1 - Mortality_Table.loc[i-1, 'q_x'])

Mortality_Table['dx'] = Mortality_Table['lx'] * Mortality_Table['q_x']
Mortality_Table

C:\Users\pablo\AppData\Local\Temp\ipykernel_1824\551017804.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '997644.9856549458' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Mortality_Table.loc[i, 'lx'] = Mortality_Table.loc[i-1, 'lx'] * (1 - Mortality_Table.loc[i-1, 'q_x'])

       t  x+t       q_x              lx            dx
0      0   36  0.001192  1000000.000000   1192.000000
1      1   37  0.001164   998808.000000   1163.014345
2      2   38  0.001233   997644.985655   1230.531513
3      3   39  0.001330   996414.454142   1325.024465
4      4   40  0.001390   995089.429677   1383.218541
5      5   41  0.001472   993706.211136   1463.062385
6      6   42  0.001552   992243.148751   1539.817643
7      7   43  0.001606   990703.331108   1591.246834
8      8   44  0.001694   989112.084273   1675.573709
9      9   45  0.001805   987436.510565   1782.418756
10    10   46  0.001954   985654.091809   1925.777969
11    11   47  0.002021   983728.313840   1988.487353
12    12   48  0.002087   981739.826488   2049.225063
13    13   49  0.002398   979690.601424   2349.043532
14    14   50  0.002660   977341.557892   2599.266174
15    15   51  0.002933   974742.291718   2858.870474
16    16   52  0.003147   971883.421244   3058.806818
17    17   53  0.003699   968824.614426   3583.368780
18    18   54  0.003863   965241.245645   3729.174438
19    19   55  0.004095   961512.071207   3937.120415
20    20   56  0.004306   957574.950792   4122.968701
21    21   57  0.004607   953451.982092   4392.703129
22    22   58  0.004938   949059.278963   4686.727218
23    23   59  0.005169   944372.551744   4881.076548
24    24   60  0.005735   939491.475197   5387.889098
25    25   61  0.006195   934103.586099   5786.982411
26    26   62  0.006591   928316.603688   6118.672751
27    27   63  0.007014   922197.930937   6468.230021
28    28   64  0.007672   915729.700916   7025.184012
29    29   65  0.008434   908704.516903   7663.885416
30    30   66  0.008970   901040.631488   8081.897648
31    31   67  0.009698   892958.733840   8660.276364
32    32   68  0.010522   884298.457476   9304.952327
33    33   69  0.011283   874993.505149   9872.156154
34    34   70  0.011997   865121.348995  10378.601870
35    35   71  0.012964   854742.747125  11080.830108
36    36   72  0.014251   843661.917017  12022.625884
37    37   73  0.015603   831639.291133  12975.826673
38    38   74  0.017092   818663.464459  13992.956850
39    39   75  0.018635   804670.507609  14995.188664
40    40   76  0.020153   789675.318945  15914.690665
41    41   77  0.021756   773760.628281  16834.300600
42    42   78  0.023534   756926.327681  17813.630226
43    43   79  0.025610   739112.697455  18928.936843
44    44   80  0.027671   720183.760612  19928.339331
45    45   81  0.030173   700255.421281  21128.533366
46    46   82  0.032744   679126.887914  22237.255395
47    47   83  0.034999   656889.632520  22990.606792
48    48   84  0.036947   633899.025728  23420.622923
49    49   85  0.039945   610478.402804  24385.683275
50    50   86  0.043437   586092.719529  25458.073545
51    51   87  0.046206   560634.645984  25904.571210
52    52   88  0.049663   534730.074775  26556.187652
53    53   89  0.053758   508173.887122  27318.200906
54    54   90  0.058097   480855.686217  27936.334772
55    55   91  0.062497   452919.351444  28305.961333
56    56   92  0.073426   424613.390112  31177.602202
57    57   93  0.085957   393435.787910  33818.432603
58    58   94  0.100918   359617.355307  36291.861117
59    59   95  0.117650   323325.494189  38039.174908
60    60   96  0.137568   285286.319281  39246.164551
61    61   97  0.161339   246040.154730  39695.937893
62    62   98  0.189787   206344.216837  39161.473239
63    63   99  0.224390   167182.743598  37514.093028
64    64  100  0.266099   129668.650570  34504.711657
65    65  101  0.324890    95163.938913  30917.812114
66    66  102  0.347570    64246.126800  22330.026292
67    67  103  0.371835    41916.100508  15585.873232
68    68  104  0.397793    26330.227276  10473.980099
69    69  105  0.425563    15856.247177   6747.832117
70    70  106  0.455272     9108.415060   4146.806341
71    71  107  0.487055     4961.608719   2416.576334
72    72  108  0.510801     2545.032384   1300.005087
73    73  109  0.535704     1245.027297    666.966103
74    74  110  0.561821      578.061194    324.766918
75    75  111  0.589211      253.294276    149.243774
76    76  112  0.617937      104.050502     64.296655
77    77  113  0.648064       39.753847     25.763037
78    78  114  0.679659       13.990810      9.508980
79    79  115  1.000000        4.481830      4.481830
80    80  116       NaN        0.000000           NaN
81    81  117       NaN             NaN           NaN
82    82  118       NaN             NaN           NaN
83    83  119       NaN             NaN           NaN
84    84  120       NaN             NaN           NaN
85    85  121       NaN             NaN           NaN
86    86  122       NaN             NaN           NaN
87    87  123       NaN             NaN           NaN
88    88  124       NaN             NaN           NaN
89    89  125       NaN             NaN           NaN
90    90  126       NaN             NaN           NaN
91    91  127       NaN             NaN           NaN
92    92  128       NaN             NaN           NaN
93    93  129       NaN             NaN           NaN
94    94  130       NaN             NaN           NaN
95    95  131       NaN             NaN           NaN
96    96  132       NaN             NaN           NaN
97    97  133       NaN             NaN           NaN
98    98  134       NaN             NaN           NaN
99    99  135       NaN             NaN           NaN
100  100  136       NaN             NaN           NaN
101  101  137       NaN             NaN           NaN
102  102  138       NaN             NaN           NaN
103  103  139       NaN             NaN           NaN
104  104  140       NaN             NaN           NaN
105  105  141       NaN             NaN           NaN
106  106  142       NaN             NaN           NaN
107  107  143       NaN             NaN           NaN
108  108  144       NaN             NaN           NaN
109  109  145       NaN             NaN           NaN
110  110  146       NaN             NaN           NaN
111  111  147       NaN             NaN           NaN
112  112  148       NaN             NaN           NaN
113  113  149       NaN             NaN           NaN
114  114  150       NaN             NaN           NaN
115  115  151       NaN             NaN           NaN

In [23]:
def tpx(x, t = 1):
    '''
    La función tpx(x+t, t) recibe la edad x y el año t.
    Devuelve la probabilidad de que un individuo con x años recien cumplidos
    sobreviva x + t años más.
    
    Si no se especifica el año t, se asume que es 1.
    '''
    l_x = None
    l_x_mas_t = None
    
    for i in range(0, len(Mortality_Table["x+t"])):
        if Mortality_Table["x+t"][i] == x:
            l_x = Mortality_Table["lx"][i]
    
    for i in range(0, len(Mortality_Table["x+t"])):
        if Mortality_Table["x+t"][i] == x + t:
            l_x_mas_t = Mortality_Table["lx"][i]
    
    if l_x is None or l_x_mas_t is None:
        raise ValueError("Edad x o x+t no encontrada en la tabla de mortalidad")
    
    return l_x_mas_t / l_x

def tqx(tpx):
    return 1 - tpx

In [24]:
edad = int(input("Introduce la edad x: "))
tiempo = int(input("Introduce el número de años a sobrevivir t: "))

supervivencia = tpx(edad, tiempo)

print("La probabilidad de sobrevivir", tiempo, " años es:", supervivencia) #43 años 22 sobrevivir, 0,91481559

La probabilidad de sobrevivir 22  años es: 0.9172317164688704

In [25]:
Mortality_Table.head()

   t  x+t       q_x              lx           dx
0  0   36  0.001192  1000000.000000  1192.000000
1  1   37  0.001164   998808.000000  1163.014345
2  2   38  0.001233   997644.985655  1230.531513
3  3   39  0.001330   996414.454142  1325.024465
4  4   40  0.001390   995089.429677  1383.218541